version: '2'
volumes:
  db-data:
    driver: local
services:
  application:
    restart: always
    build: .
    container_name: chord-app
    command: npm start dev
    depends_on:
     - mongo
    tty: true
    ports:
     - "8443:8443"
     - "35729:35729"
    environment:
     - PORT=8443
     - MONGODB_URI=mongodb://mongo/chord-dev
     - LIVERELOAD=true
     - SPOTIFY_CLIENT_ID=e5f6b758cb314e1aadb6295f1f672a0d
     - SPOTIFY_SECRET=fdb0b182dcae4456b0cc896512deadca
     - SPOTIFY_URI=http://localhost:8443/spotifyURI
     - NODE_ENV = development
    volumes:
     - ./:/opt/chord
     - ./node_modules:/opt/chord/node_modules
  mongo:
    image: mongo
    container_name: chord-mongodb
    restart: always
    tty: true
    ports:
     - "27017:27017"
    volumes:
     - db-data:/data/db
